config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'

  resources :entries
  get 'entry_reports', to: 'entries#reports'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  validates :value, numericality: true
  validates :value, presence: true
  validate :no_more_than_four_entries_per_day

  def no_more_than_four_entries_per_day
    if Entry.entries_today.length >= 4
      errors.add(:value, "exceeds the number of allowed entries (4/day)")
    end
  end

  def self.entries_today
    Entry.where("created_at >= ?", Time.zone.now.beginning_of_day)
  end

  def self.mean
    entry_matches = self.entries_today
    if entry_matches.length == 0
      return 0
    else
      sum = 0
      entry_matches.each do |entry|
        sum += entry.value
      end
      return sum / entry_matches.size
    end
  end

  def self.max
    entry_matches = self.entries_today
    if entry_matches.length == 0
      return 0
    else
      max = 0
      entry_matches.each do |entry|
        max = entry.value if entry.value > max
      end
      return max
    end
  end

  def self.min
    entry_matches = self.entries_today
    if entry_matches.length == 0
      return 0
    else
      min = entry_matches.first.value
      entry_matches.each do |entry|
        min = entry.value if entry.value < min
      end
      return min
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    entries_today = Entry.entries_today.length
    if entries_today == 1
      @entrycount_message = "#{entries_today} entry today."
    else
      @entrycount_message = "#{entries_today} entries today."
    end
  end
  def new
    @entry = Entry.new
  end
  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      flash[:notice] = "Entry added!"
      redirect_to :action => 'index'
    else
      flash[:error] = ""
      messages = @entry.errors.messages[:value]
      messages.each do |message|
        flash[:error] += "Value " + message + ". "
      end
      if messages.include? "exceeds the number of allowed entries (4/day)"
        redirect_to :action => 'index'
      else
        render :new
      end

    end
  end
  def reports
    if Entry.entries_today.length == 0
      @mean_msg = "Mean Average: Insufficient data"
      @max_msg = "Maximum Value: Insufficient data"
      @min_msg = "Minimum Value: Insufficient data"
    else
      @mean_msg = "Mean Average: " + Entry.mean.to_s
      @max_msg = "Maximum Value: " + Entry.max.to_s
      @max_msg = "Minimum Value: " + Entry.min.to_s
    end
    render :reports
  end
  private
    def entry_params
      params.require(:entry).permit(:value)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/index.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= link_to "Glucose Reading", new_entry_path, class: "btn btn-default btn-lg btn-block" %>
  <%= link_to "Reading Reports", entry_reports_path, class: "btn btn-default btn-lg btn-block" %>
</div>
<%= @entrycount_message %>

app/views/entries/new.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          New Entry
        </h3>
      </div>
      <div class="panel-body">
        <%= form_for @entry do |f| %>
          <span id="new_question_errors"></span>
          <div class="form-group">
            <%= f.text_field :value %>
          </div>
          <%= f.submit "Create Entry", class: "btn btn-warning" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/entries/reports.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          Reports
        </h3>
      </div>
      <div class="panel-body">
        <%= @mean_msg %>
        <%= @max_msg %>
        <%= @min_msg %>
      </div>
    </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweety</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            Sweety
          </h3>
        </div>
        <div class="panel-body">

          <%= yield %>
        </div>
      </div>
    </div>
  </div>

</body>
</html>